//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23dh171095_MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProDetID { get; set; }
        public decimal Price { get; set; }
        public int RemainQuantity { get; set; }
        public int SoldQuantity { get; set; }
        public int ViewQuantity { get; set; }
        public int ProductProductID { get; set; }
        public int SupplierSupID { get; set; }
        public int ColorColorId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
